-- Generated by nvim/lua/zenwritten_compile.lua - do not edit by hand;
-- change the configuration there and recompile instead.
return {
  ["zenwritten dark"] = {
    ansi = { "#191919", "#DE6E7C", "#819B69", "#B77E64", "#6099C0", "#B279A7", "#66A5AD", "#BBBBBB" },
    background = "#171213",
    brights = { "#3D3839", "#E8838F", "#8BAE68", "#D68C67", "#61ABDA", "#CF86C1", "#65B8C1", "#8E8E8E" },
    cursor_bg = "#BBBBBB",
    cursor_border = "#BBBBBB",
    cursor_fg = "#171213",
    foreground = "#BBBBBB",
    selection_bg = "#3D3839",
    selection_fg = "#BBBBBB",
    split = "#3D3839"
  },
  ["zenwritten light"] = {
    ansi = { "#EEEEEE", "#A8334C", "#4F6C31", "#944927", "#286486", "#88507D", "#3B8992", "#353535" },
    background = "#EEEEEE",
    brights = { "#C6C3C3", "#94253E", "#3F5A22", "#803D1C", "#1D5573", "#7B3B70", "#2B747C", "#5C5C5C" },
    cursor_bg = "#353535",
    cursor_border = "#353535",
    cursor_fg = "#EEEEEE",
    foreground = "#353535",
    selection_bg = "#C6C3C3",
    selection_fg = "#353535",
    split = "#C6C3C3"
  }
}
