-- zenwritten, compiled flat: the highlights lush would have built at
-- startup, written down once instead (lua/zenwritten_palette/).
-- Generated by lua/zenwritten_compile.lua - do not edit by hand;
-- change the configuration there and recompile instead.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "zenwritten"

local bg = vim.o.background == "light" and "light" or "dark"
local set = require("zenwritten_palette." .. bg)
for name, attrs in pairs(set.hl) do
  vim.api.nvim_set_hl(0, name, attrs)
end
for i, colour in ipairs(set.terminal) do
  vim.g["terminal_color_" .. (i - 1)] = colour
end
