-- The statusline's colours, for whichever background is current when
-- lualine asks.
-- Generated by lua/zenwritten_compile.lua - do not edit by hand;
-- change the configuration there and recompile instead.
local themes = {
dark = {
  command = {
    a = {
      bg = "#65435E",
      fg = "#A3A3A3",
      gui = "bold"
    }
  },
  inactive = {
    a = {
      bg = "#242424",
      fg = "#CFCFCF",
      gui = "bold"
    },
    b = {
      bg = "#242424",
      fg = "#CFCFCF"
    },
    c = {
      bg = "#242424",
      fg = "#CFCFCF"
    }
  },
  insert = {
    a = {
      bg = "#324757",
      fg = "#A3A3A3",
      gui = "bold"
    }
  },
  normal = {
    a = {
      bg = "#525252",
      fg = "#A3A3A3",
      gui = "bold"
    },
    b = {
      bg = "#3E3E3E",
      fg = "#A3A3A3"
    },
    c = {
      bg = "#2A2A2A",
      fg = "#BBBBBB"
    }
  },
  replace = {
    a = {
      bg = "#3E2225",
      fg = "#A3A3A3",
      gui = "bold"
    }
  },
  visual = {
    a = {
      bg = "#404040",
      fg = "#A3A3A3",
      gui = "bold"
    }
  }
},
light = {
  command = {
    a = {
      bg = "#DEB9D6",
      fg = "#505050",
      gui = "bold"
    }
  },
  inactive = {
    a = {
      bg = "#DDDDDD",
      fg = "#686868",
      gui = "bold"
    },
    b = {
      bg = "#DDDDDD",
      fg = "#686868"
    },
    c = {
      bg = "#DDDDDD",
      fg = "#686868"
    }
  },
  insert = {
    a = {
      bg = "#A9BED1",
      fg = "#505050",
      gui = "bold"
    }
  },
  normal = {
    a = {
      bg = "#AEAEAE",
      fg = "#505050",
      gui = "bold"
    },
    b = {
      bg = "#C1C1C1",
      fg = "#505050"
    },
    c = {
      bg = "#D7D7D7",
      fg = "#353535"
    }
  },
  replace = {
    a = {
      bg = "#EBD8DA",
      fg = "#505050",
      gui = "bold"
    }
  },
  visual = {
    a = {
      bg = "#D7D7D7",
      fg = "#505050",
      gui = "bold"
    }
  }
},
}
return vim.deepcopy(themes[vim.o.background] or themes.dark)
